-h, --help                                                                                     │
│     show this help message and exit                                                            │
│ --source STR, -s STR                                                                           │
│     path to the source portrait (human/animal) or video (human) (default:                      │
│     /content/LivePortrait/src/config/../../assets/examples/source/s0.jpg)                      │
│ --driving STR, -d STR                                                                          │
│     path to driving video or template (.pkl format) (default:                                  │
│     /content/LivePortrait/src/config/../../assets/examples/driving/d0.mp4)                     │
│ --output-dir STR, -o STR                                                                       │
│     directory to save output video (default: animations/)                                      │
│ --flag-use-half-precision, --no-flag-use-half-precision                                        │
│     whether to use half precision (FP16). If black boxes appear, it might be due to GPU        │
│     incompatibility; set to False. (default: True)                                             │
│ --flag-crop-driving-video, --no-flag-crop-driving-video                                        │
│     whether to crop the driving video, if the given driving info is a video (default: False)   │
│ --device-id INT                                                                                │
│     gpu device id (default: 0)                                                                 │
│ --flag-force-cpu, --no-flag-force-cpu                                                          │
│     force cpu inference, WIP! (default: False)                                                 │
│ --flag-normalize-lip, --no-flag-normalize-lip                                                  │
│     whether to let the lip to close state before animation, only take effect when              │
│     flag_eye_retargeting and flag_lip_retargeting is False (default: True)                     │
│ --flag-source-video-eye-retargeting, --no-flag-source-video-eye-retargeting                    │
│     when the input is a source video, whether to let the eye-open scalar of each frame to be   │
│     the same as the first source frame before the animation, only take effect when             │
│     flag_eye_retargeting and flag_lip_retargeting is False, may cause the inter-frame          │
│     jittering (default: False)                                                                 │
│ --flag-video-editing-head-rotation, --no-flag-video-editing-head-rotation                      │
│     when the input is a source video, whether to inherit the relative head rotation from the   │
│     driving video (default: False)                                                             │
│ --flag-eye-retargeting, --no-flag-eye-retargeting                                              │
│     not recommend to be True, WIP; whether to transfer the eyes-open ratio of each driving     │
│     frame to the source image or the corresponding source frame (default: False)               │
│ --flag-lip-retargeting, --no-flag-lip-retargeting                                              │
│     not recommend to be True, WIP; whether to transfer the lip-open ratio of each driving      │
│     frame to the source image or the corresponding source frame (default: False)               │
│ --flag-stitching, --no-flag-stitching                                                          │
│     recommend to True if head movement is small, False if head movement is large or the source │
│     image is an animal (default: True)                                                         │
│ --flag-relative-motion, --no-flag-relative-motion                                              │
│     whether to use relative motion (default: True)                                             │
│ --flag-pasteback, --no-flag-pasteback                                                          │
│     whether to paste-back/stitch the animated face cropping from the face-cropping space to    │
│     the original image space (default: True)                                                   │
│ --flag-do-crop, --no-flag-do-crop                                                              │
│     whether to crop the source portrait or video to the face-cropping space (default: True)    │
│ --driving-option {expression-friendly,pose-friendly}                                           │                                                                                        │
│     expression-friendly or pose-friendly expression-friendly would adapt the driving           │
│     motion with the global multiplier, and could be used when the source is a human image      │
│     (default: expression-friendly)                                                             │
│ --driving-multiplier FLOAT                                                                     │
│     be used only when driving_option is "expression-friendly" (default: 1.0)                   │
│ --driving-smooth-observation-variance FLOAT                                                    │
│     smooth strength scalar for the animated video when the input is a source video, the larger │
│     the number, the smoother the animated video; too much smoothness would result in loss of   │
│     motion accuracy (default: 3e-07)                                                           │
│ --audio-priority {source,driving}                                                              │
│     whether to use the audio from source or driving video (default: driving)                   │
│ --det-thresh FLOAT                                                                             │
│     detection threshold (default: 0.15)                                                        │
│ --scale FLOAT                                                                                  │
│     the ratio of face area is smaller if scale is larger (default: 2.3)                        │
│ --vx-ratio FLOAT                                                                               │
│     the ratio to move the face to left or right in cropping space (default: 0)                 │
│ --vy-ratio FLOAT                                                                               │
│     the ratio to move the face to up or down in cropping space (default: -0.125)               │
│ --flag-do-rot, --no-flag-do-rot                                                                │
│     whether to conduct the rotation when flag_do_crop is True (default: True)                  │
│ --source-max-dim INT                                                                           │
│     the max dim of height and width of source image or video, you can change it to a larger    │
│     number, e.g., 1920 (default: 1280)                                                         │
│ --source-division INT                                                                          │
│     make sure the height and width of source image or video can be divided by this number      │
│     (default: 2)                                                                               │
│ --scale-crop-driving-video FLOAT                                                               │
│     scale factor for cropping driving video (default: 2.2)                                     │
│ --vx-ratio-crop-driving-video FLOAT                                                            │
│     adjust y offset (default: 0.0)                                                             │
│ --vy-ratio-crop-driving-video FLOAT                                                            │
│     adjust x offset (default: -0.1)                                                            │
│ --server-port INT, -p INT                                                                      │
│     port for gradio server (default: 8890)                                                     │
│ --share, --no-share                                                                            │
│     whether to share the server to public (default: False)                                     │
│ --server-name {None}|STR                                                                       │
│     set the local server name, "0.0.0.0" to broadcast all (default: 127.0.0.1)                 │
│ --flag-do-torch-compile, --no-flag-do-torch-compile                                            │
│     whether to use torch.compile to accelerate generation (default: False)                     │
│ --gradio-temp-dir {None}|STR                                                                   │
│     directory to save gradio temp files (default: None)                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────╯
